service: sls-liquid-imobiliaria
frameworkVersion: "4"

custom: 
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.9
  region: sa-east-1
  stage: dev

functions:
  obterPrecoMedio:
    handler: handler.main
    events:
      - httpApi:
          path: /precos
          method: get